#+LANGUAGE: ro
#+AUTHOR: Redacția «Știința Marxism», tradus de Pavel Morozov
#+TITLE: Stalin și întrebarea construcției socialismului în URSS

#+LATEX: \setstretch{1.6}

Până în prezent nu se mai calmează cerțile referitor la construcția
socialismului în URSS.

Astăzi această întrebare este foarte importantă pentru mișcarea marxistă. Demult
e timpul ca marxiștii să dezvolte o linie unită referitor la multe întrebări
pentru posibilitatea viitoarelor uniri a diferitor organizații. Dar, cum se
cunoaște, pentru a ne uni trebuie mai întâi să ne dezbinăm. Această publicație
este anume despre pozițiile antimarxiste, de la care trebuie să ne dezbinăm,
despre socialismul în URSS și poziția lui Stalin referitor la această întrebare.

Astăzi există două tabere principale care sunt împărțite în opinia lor referitor
la construcția unei societăți socialiste în URSS.

*Prima tabără* - este tabăra troțkiștilor și altor puteri antimarxiste. Aceștia
iubesc prea mult să-și bată joc de experiența construcției socialismului în
URSS, să-și bată joc de «prostuțul Stalin» care, presupun ei, ar fi «declarat»
victoria «completă» și «finală» a socialismului în URSS, care «din cauza
prostiei sale și neștiință a marxismului» își imagina o societate completă
socialistă, drept o economie în care sunt prezenți banii, producția de mărfuri
și legea valorii.

*A doua tabără* - este tabăra «staliniștilor» formali, în realitate fiind
«marxiști» estetici, care idealizează Uniunea Sovietică cu declarațiile lor
despre construcția completă a unei societăți socialiste, adică nu derivă analiza
lor din realitate, ci din propriile gânduri, ceea ce fără îndoială este
idealism.

Pentru a înțelege toate astea, vom analiza aspectul teoretic al lui Stalin
despre socialismul într-o singură țară, vom trece pe scurt etapele dezvoltării
socialismului în URSS și îi vom permite vorbi însăși tovarășului Stalin, care va
pune un punct destul de clar în această ceartă.

/Prima întrebare/, care trebuie să fie clarificată pentru noi, *este poziția
teoretică a lui Stalin despre posiblitatea victoriei socialismului în URSS.*

Pentru prima dată el *a concretizat* și *a dezvoltat* poziția lui Lenin despre
posibilatatea victoriei socialismului în URSS în opera sa «Despre bazele
leninismului» în 1924:

#+begin_quote
«Dar să răsturnăm domnia burgheziei și să instalăm domnia proletariatului într-o
țară - încă nu înseamnă să asigurăm o victorie completă a
socialismului. Întărindu-și domnia și ghidând țărănimea, proletariatul țării
învingătoare poate și trebuie să construiască o societate socialistă.

Dar înseamna aceasta că atunci se va atinge o victorie completă a
socialismului, adică înseamnă oare aceasta că proletariatul va putea, cu
puterile unei singuri țări să întărească permanent socialismul și să garanteze
siguranța țării de la intervenții, deci, de la restaurație?

Nu, nu înseamnă. Pentru aceasta este necesară victoria revoluției în cel puțin
câteva țări. Iată de ce dezvoltarea și suportul revoluției în alte țări
constituie o sarcină substanțială a revoluției victorioase. De aceasta revoluția
țării învingătoare trebuie să se considere nu ca ceva autosuficient, ci ca un
ajutor, ca un mijloc de accelerare a victoriei proletariatului în alte țări»

(I. Stalin. «Despre bazele leninismului» - trad. Pavel Morozov)
#+end_quote

Mai concret și exact Iosif Vissarionovici a dezvoltat teoria victoriei
socialismului într-o singură țară și a revoluției socialiste, ca un proces
mondial, în lucrarea sa "Răspuns tovarășului Ivanov, Ivan Filippovici", care era
scrisă în anul 1938:

#+begin_quote
«Întrebarea victoriei socialismului într-o singură țară - în cazul dat în țara
noastră - are fără îndoială două părți deosebite.

Prima parte a întrebării victoriei socialismului în țara noastră se referă la
problema relațiilor claselor înăuntrul țării noastre. Aceasta-i regiunea
relațiilor interne. Poate oare clasa muncitoare a țării noastre să rezolve
contradicțiile cu țărănimea noastră și să stabilească o uniune cu ea? Poate oare
clasa muncitoare a țării noastre în uniune cu țărănimea să distrugă burghezia
țării noastre, să preia pământurile, fabricile, miniile, etc. și să construiască
cu propriile puteri o societate nouă, fără clase, o societate completă
socialistă?...

...Leninismul răspunde la aceste întrebări pozitiv. Lenin ne învață, că "Avem
toate cele necesare pentru construcția unei societăți complete socialiste"...

...A doua parte a întrebării victoriei socialismului cuprinde problema
relațiilor țării noastre cu alte țări, cu țări capitaliste, problema relațiilor
clasei muncitoare a țării noastre cu burghezia altor țări. Aceasta-i regiunea
relațiilor externe, internaționale. Poate oare socialismul învingător a unei
țări, fiind înconjurat de multe țări capitaliste puternice, să se considere
complet garantat și protejat de pericolul invaziei din exterior (intervenție) și
de la încercări de a reinstala capitalismul în țara noastră? Poate oare clasa
noastră muncitoare și țărănimea noastră cu puterile proprii, fără ajutor serios
din partea muncitorilor altor țări să învingă burghezia altor țări la fel cum au
făcut-o cu burghezia proprie? Altfel: putem considera victoria socialismului în
țara noastră a fi definitivă, permanentă, protejată de pericolul invaziei
militare exterioare și de la încercări de restaurație a capitalismului, cu
condiția că victoria socialismului este prezentă într-o singură țară, iar
înconjurarea capitalistă continuă să existe?...

...Leninismul răspunde la aceste probleme negativ. Leninismul ne învață, că
"victoria definitivă a socialismului, în sensul garanției complete de la
restaurație a relațiilor burgheze este posibilă doar pe scară mondială" (vezi
cunoscuta rezoluție a conferenției a XIV-a al Partidului Comunist al URSS).
Aceasta înseamnă că ajutorul serios a proletariatului internațional constituie
acea putere, fără care nu poate fi completată sarcina victoriei socialismului
definitivă într-o singură țară»

(I. Stalin. «Răspuns tovarășului Ivanov, Ivan Filippovici» - trad. Pavel
Morozov).
#+end_quote

Clarificându-ne cu baza teoretică a lui I. V. Stalin despre posibilitatea
victoriei socialismului într-o singură țară, să trecem la «declarațiile» lui
despre «construcția completă a societății socialiste» în URSS. Pentru aceasta ne
vom întoarce din nou la lucrarea sa «Răspuns tovarășului Ivanov, Ivan
Filippovici»:

#+begin_quote
«Reiese, că această întrebare conține două probleme deosebite:
1. Problema relațiilor interne a țării noastre, adică problema învingerii
   burgheziei noastre și construcției socialismului complet, și
2. Problema relațiilor externe a țării noastre, adică problema protecției țării
   noastre de la intervenție militară și restaurație.

Prima problemă este deja rezolvată de noi, pentru că burghezia noastră este deja
lichidată și socialismul este CONSTRUIT ÎN PRINCIPAL.»
(I. Stalin. «Răspuns tovarășului Ivanov, Ivan Filippovici» - trad. Pavel
Morozov).
#+end_quote

Din acest citat este clar, că societatea socialistă în URSS era construită
incomplet, că era construită doar ÎN PRINCIPAL, adică la nivel de bază, care
presupunea distrugerea sistemului de exploatație a omului de către alt om și
exproprierea burgheziei. Din această afirmație a lui Stalin, inconsecvența
declarațiilor precum că Stalin a declarat despre victoria completă a
socialismului în URSS. Formularea despre construcția socialismului în principal
și despre faptul că socialismul continuă să fie construit în multe opere sau
discursuri ale lui Stalin. În calitate de dovadă, aducem încă câteva citate:

#+begin_quote
«Societatea noastră sovietică a realizat construcția în principal a
socialismului, a creat un sistem socialist, adică a realizat ceea ce marxiștii
numesc altfel prima fază, sau faza inferioară a comunismului. Înseamnă, la noi
deja este REALIZATĂ ÎN PRINCIPAL prima fază a comunismului, socialismul»

(I. Stalin. «Despre proiectul Constituției Uniunii RSS: Raport la congresul de
urgență Unional al Sovieților la 25 noiembrie 1936» - trad. Pavel Morozov).
#+end_quote

Și încă:

#+begin_quote
«Societatea noastră sovietică este una socialistă, pentru că proprietatea privată
asupra fabricilor, pământului, băncilor, mijloacele de transport este
desființată. Acea organizație socială, pe care am creat-o, poate fi numită o
organizație sovietică, socialistă, încă nefinisată deplin, dar în principal
fiind o organizație socialistă a societății.»

(I. Stalin. «Conversație cu președintele asociației americane de ziare
„Scripps-Howard Newspapers”, domnul Roy Howard la 1 martie 1936.» - trad. Pavel
Morozov).
#+end_quote

Și încă:

#+begin_quote
«În acest timp am reușit deja să lichidăm burghezia proprie, să stabilim o
relație fraterne cu țărănimea noastră și să construim în principal societatea
socialistă, în ciuda lipsei victoriei revoluției socialiste în alte țări.»

(I. Stalin. «Răspuns tovarășului Ivanov, Ivan Filippovici» - trad. Pavel
Morozov).
#+end_quote

Și încă:

#+begin_quote
«Problema dispariției diferențelor dintre oraș (industrie) și sat (agricultură),
dintre munca fizică și intelectuală. Această problemă nu a fost pusă de clasicii
marxismului. Această problemă este nouă, pusă de practica noastră de CONSTRUCȚIE
A UNEI SOCIETĂȚÎ SOCIALISTE»

(I. Stalin. «Problemele economice a socialismului în URSS»).
#+end_quote

De asemenea troțkiștii și alți conductori a ideologiei burgheze în mișcarea
muncitorească iubesc să-și bată joc de "prostul" Stalin, care, se prespune,
descria o sociatate socialistă completă drept una cu prezența producției de
mărfuri, legea valorii și banii prezenți în schimb. Aceste declarații ale
antimarxiștilor nu sunt mai mult decât un semn a incompetenței lor
intelectuale.

Pentru a evidenția falsitatea acestor afirmații, trebuie să clarificăm etapele
construcției socialiste în URSS. Vom evidenția *dezvoltarea socialismului în
URSS în 3 etape:*

1. *Prima etapă* - etapa capitalismului de stat-monopol *multiform*, care a fost
   observată până în jurul anilor 1935-36, în care *schimbul și producția
   capitaliste de mărfuri sunt în plină desfășurare*, iar exploatarea omului de
   către om este păstrată. Această etapă în ansamblu se caracterizează prin
   lupta structurilor economice, lupta pentru exproprierea capitaliștilor din
   oraș și țară.

2. *A doua etapă* - etapa capitalismului de stat-monopol proletar, care se
   observă *din anii 1935-36 până în 1953*, unde burghezia orașului și a satului a
   fost expropriată, unde este distrusă exploatarea omului de către om, unde
   schimbul de mărfuri capitalist (monetar) a fost limitat la lucrurile necesare
   proletariatului, ceea ce constituie DEZVOLTAREA capitalismului fără
   capitaliști, de însăși proletariatul țării cu scopul de a DISTRUGE
   capitalismul. Aceasta este *construcția socialismului în principal*, adică în
   baza sa. Sarcina construcției unei societăți socialiste complete încă stătea
   în față.

   Unii manipulatori iubesc să aplice acestei perioade definiția lui Lenin:
   *«...socialismul este monopolia de stat capitalistă pusă spre folosul
   întregului popor și așadar nemaifiind monopolie.»*
   Dar această utilizare este *incorectă fundamental!* Pentru că în URSS existau
   *trei forme a proprietății*:

   - *De stat* (unde lucra proletariatul);
   - *De cooperativ* (kolhozurile, cooperația industrială);
   - *Personală* (ultimele două sunt versiuni limitate a proprietății
     mic-burgheze);

   *Sfera de stat* era proletarizată, adică era controlată de producția
   planificată și *era, într-o anumită măsură, pusă spre folosul întregului*
   *popor (altfel convertirea proprietății în proprietate «populară»[fn:1] este*
   *posibilă doar când întreaga societate a devenit omogen compusă din*
   *proletari),* dar trebuie notat că proprietatea de stat îi aparținea
   proletariatului, organizat într-un stat, și din motivul caruia constituind
   proprietatea colectivă privată a proletariatului, servind în primul rând
   intereselor proletariatului, și doar în unele momente fiind folosită pentru
   beneficiul întregului popor (adică folosind termenul «proprietate populară»
   pentru a descrie acest tip de proprietate este incorect, în folosirea acestui
   termen Stalin a comis o eroare), atunci când proprietatea de kolhozuri și cea
   personală nu erau atinse de plan, nu era ridicată, cu cuvintele lui Stalin,
   la nivelul proprietății "populare", adică nu era la un nivel oarecare pusă
   spre folosul «întregului popor», dar exprima exclusiv interesele micii
   burghezii (cooperatori, kolhoznici, artizani, ș.a.), din care cauză plasarea
   acestei etape la nivelul etapei socialismului, drept monopolia de stat
   capitalistă pusă spre folosul întregului popor -- este fundamental greșit.

3. *A treia etapă* - este etapa capitalismului de stat-monopol *sub dictatura
   burgheziei*, care în URSS a durat din *1953 până în 1991*. Această etapă este
   caracterizată prin distrugerea treptată a tuturor realizărilor societății de
   construcție a socialismului, prin dezvoltarea treptată a producției de
   mărfuri, prin reabilitarea metodelor capitaliste de organizare a producției,
   prin reabilitarea treptată a relațiilor deplin capitalite. Dar această etapă
   nu este tema discuției noastre deoarece nu are de-a face nici cu Stalin, nici
   cu construcția socialismului.


Iar Stalin, în lucrearea sa "Problemele economice a socialismului în URSS",
arată clar căile spre construcția societății socialiste complete prin
transformarea kolhozurilor în sovhozuri, distrugerea schimbului de marfă (asta
va distruge și schimbul monetar și legea valorii. - O. St.). Iată ce spune
Stalin în această lucrare privind distrugerea schimbului de mărfuri în URSS:

#+begin_quote
«Într-al doilea rând, este necesară, prin calea trecerilor treptate, efectuate
în beneficiul kolhozurilor și, respectiv, pentru întreaga societate, ridicarea
proprietății de kolhoz la nivel de proprietate populară (adică transformarea lor
în Sovhozuri. - O. St.), iar schimbul de mărfuri la fel prin tranziții treptate
de înlocuit cu sistema schimbului de produs, pentru ca puterea centalizată sau
un alt centru socio-economic să poată acoperi toate produsele producției sociale
în interesul societății»

(I. Stalin. «Problemele economice ale socialismului în URSS» - trad. Pavel
Morozov).
#+end_quote

În acest mod va fi lichidată legea valorii și schimbul monetar, ce am notat mai
sus:

#+begin_quote
«Valoarea, drept legea valorii, este o categorie istorică, legată cu existența
producției de mărfuri. Cu lichidarea producției de mărfuri vor dispărea și
valoarea cu formele ei și legea valorii»

(I. Stalin. «Problemele economice ale socialismului în URSS» - trad. Pavel
Morozov).
#+end_quote


Concluzie:

Din toate cele spuse mai sus este evident, că prima grupă, adică troțkiștii și
alte elemente mic-burgheze se înșeală evident, atribuind lui Stalin atât
declarațiile despre construcția unei societăți complete socialiste, cât și
declarațiile despre societății complete socialiste, în care există schimbul de
mărfuri monetar  și legea valorii.

În URSS socialismul nu a fost construit, au fost pus doar fundamentul economiei
socialiste, mai precis capitalismul de stat-monopol sub conducerea
proletariatului, ca o treaptă necesară și finală în direcția socialismului. Aici
poate fi adusă o analogie cu un atlet ce trebuie să fugă pe o distanță de 100
metri, dar până acum a fugit doar 70m, deci *în principal* distanța este
trecută, însă dacă să analizăm acest lucru complet, să gândim dialectic, adică
să ținem cont de legătura reciprocă între lucruri - atletul nu a fugit întreaga
distanță, adică nu a finisat distanța de 100m. La fel și socialismul în URSS,
era construit doar în principal, dar până la sfârșit nu a fost construit.

În general, aceasta este poziția lui Stalin și a «Științei Marxism» referitor la
întrebarea construcției socialismului în URSS.

[fn:1] Notiță de traducător - «общенародная» în rusă are sens de proprietate a
întregului popor, adică proprietate a ABSOLUT TUTUROR oamenilor, și nu ca
proprietate «publică» în statele burgheze capitaliste de astăzi.
